THEMES = {
    "Fiber Optics & Connectivity": ["AXTI", "AAOI", "LITE", "CIEN", "COHR", "VIAV", "INFN", "COMM", "IPGP"],
    "Memory & Storage": ["MU", "WDC", "STX", "SNDK", "NTAP", "PURE", "SIMO"],
    "AI Related Energy": ["BE", "AMPX", "POWL", "FTAI", "TE", "FCEL", "PLUG", "BLDP"],
    "Semiconductor Equipment": ["LRCX", "AMAT", "KLAC", "TER", "FORM", "ONTO", "ACLS", "CAMT", "ICHR", "ENTG"],
    "Cooling": ["VRT", "SMCI", "AAON", "MOD", "JCI", "TT"],
    "Computing & AI Software": ["MRVL", "APP", "DELL", "TTMI", "FSLY", "NET", "SNOW", "DDOG", "MDB"],
    "Crypto": ["COIN", "HOOD", "MSTR", "RIOT", "MARA", "CLSK", "CIFR", "HUT", "IREN", "APLD", "CORZ"],
    "Data Center": ["EQIX", "DLR", "AMT", "VRT", "APLD", "NBIS", "IREN", "CIFR", "CORZ"],
    "Defense & Aerospace": ["LMT", "RTX", "NOC", "GD", "KTOS", "PLTR", "CACI", "SAIC", "RKLB", "ASTS"],
    "Biotech & Pharma": ["MRNA", "BNTX", "VRTX", "REGN", "BIIB", "AMGN", "GILD", "HIMS", "QURE", "BHVN", "CAPR"],
    "EV & Clean Energy": ["TSLA", "RIVN", "LCID", "NIO", "XPEV", "LI", "CHPT", "BLNK", "EVGO"],
    "Cybersecurity": ["CRWD", "ZS", "PANW", "S", "FTNT", "OKTA", "CYBR", "SAIL"],
    "Cloud & SaaS": ["CRM", "NOW", "ADBE", "ORCL", "INTU", "WDAY", "TEAM", "HUBS"],
    "Semiconductors": ["NVDA", "AMD", "INTC", "QCOM", "AVGO", "TXN", "ARM", "MCHP", "SWKS", "QRVO"],
    "Oil & Gas": ["XOM", "CVX", "OXY", "COP", "EOG", "SLB", "HAL", "WTI", "BATL"],
}

MARKET_OVERVIEW = [
    {"symbol": "^GSPC", "label": "S&P 500", "group": "Major Indexes"},
    {"symbol": "^IXIC", "label": "Nasdaq Composite", "group": "Major Indexes"},
    {"symbol": "^DJI", "label": "Dow Jones", "group": "Major Indexes"},
    {"symbol": "^RUT", "label": "Russell 2000", "group": "Major Indexes"},
    {"symbol": "SPY", "label": "SPDR S&P 500 ETF", "group": "Risk Assets"},
    {"symbol": "QQQ", "label": "Invesco QQQ", "group": "Risk Assets"},
    {"symbol": "IWM", "label": "iShares Russell 2000", "group": "Risk Assets"},
    {"symbol": "SMH", "label": "VanEck Semiconductor ETF", "group": "Risk Assets"},
    {"symbol": "GLD", "label": "SPDR Gold Shares", "group": "Macro"},
    {"symbol": "TLT", "label": "20+ Year Treasury", "group": "Macro"},
    {"symbol": "USO", "label": "United States Oil Fund", "group": "Macro"},
    {"symbol": "BTC-USD", "label": "Bitcoin", "group": "Digital Assets"},
]

SECTOR_ETFS = [
    {"symbol": "XLB", "label": "Materials", "group": "Sectors"},
    {"symbol": "XLC", "label": "Communication Services", "group": "Sectors"},
    {"symbol": "XLE", "label": "Energy", "group": "Sectors"},
    {"symbol": "XLF", "label": "Financials", "group": "Sectors"},
    {"symbol": "XLI", "label": "Industrials", "group": "Sectors"},
    {"symbol": "XLK", "label": "Technology", "group": "Sectors"},
    {"symbol": "XLP", "label": "Consumer Staples", "group": "Sectors"},
    {"symbol": "XLRE", "label": "Real Estate", "group": "Sectors"},
    {"symbol": "XLU", "label": "Utilities", "group": "Sectors"},
    {"symbol": "XLV", "label": "Health Care", "group": "Sectors"},
    {"symbol": "XLY", "label": "Consumer Discretionary", "group": "Sectors"},
]

ETF_UNIVERSE = [
    {"symbol": "SPY", "label": "SPDR S&P 500", "group": "Broad Market"},
    {"symbol": "QQQ", "label": "Invesco QQQ", "group": "Broad Market"},
    {"symbol": "DIA", "label": "SPDR Dow Jones", "group": "Broad Market"},
    {"symbol": "IWM", "label": "iShares Russell 2000", "group": "Broad Market"},
    {"symbol": "VTI", "label": "Vanguard Total Stock Market", "group": "Broad Market"},
    {"symbol": "RSP", "label": "Invesco Equal Weight S&P 500", "group": "Broad Market"},
    {"symbol": "IWB", "label": "iShares Russell 1000", "group": "Broad Market"},
    {"symbol": "IWF", "label": "iShares Russell 1000 Growth", "group": "Style & Factors"},
    {"symbol": "IWD", "label": "iShares Russell 1000 Value", "group": "Style & Factors"},
    {"symbol": "IWO", "label": "iShares Russell 2000 Growth", "group": "Style & Factors"},
    {"symbol": "IWN", "label": "iShares Russell 2000 Value", "group": "Style & Factors"},
    {"symbol": "MTUM", "label": "iShares Momentum", "group": "Style & Factors"},
    {"symbol": "QUAL", "label": "iShares Quality", "group": "Style & Factors"},
    {"symbol": "XLB", "label": "Materials", "group": "Sectors"},
    {"symbol": "XLC", "label": "Communication Services", "group": "Sectors"},
    {"symbol": "XLE", "label": "Energy", "group": "Sectors"},
    {"symbol": "XLF", "label": "Financials", "group": "Sectors"},
    {"symbol": "XLI", "label": "Industrials", "group": "Sectors"},
    {"symbol": "XLK", "label": "Technology", "group": "Sectors"},
    {"symbol": "XLP", "label": "Consumer Staples", "group": "Sectors"},
    {"symbol": "XLRE", "label": "Real Estate", "group": "Sectors"},
    {"symbol": "XLU", "label": "Utilities", "group": "Sectors"},
    {"symbol": "XLV", "label": "Health Care", "group": "Sectors"},
    {"symbol": "XLY", "label": "Consumer Discretionary", "group": "Sectors"},
    {"symbol": "TLT", "label": "20+ Year Treasury", "group": "Rates & Credit"},
    {"symbol": "IEF", "label": "7-10 Year Treasury", "group": "Rates & Credit"},
    {"symbol": "SHY", "label": "1-3 Year Treasury", "group": "Rates & Credit"},
    {"symbol": "TIP", "label": "Treasury Inflation-Protected", "group": "Rates & Credit"},
    {"symbol": "HYG", "label": "High Yield Corporate Bond", "group": "Rates & Credit"},
    {"symbol": "LQD", "label": "Investment Grade Corporate Bond", "group": "Rates & Credit"},
    {"symbol": "JNK", "label": "High Yield Bond", "group": "Rates & Credit"},
    {"symbol": "EMB", "label": "Emerging Market Bonds", "group": "Rates & Credit"},
    {"symbol": "GLD", "label": "SPDR Gold Shares", "group": "Commodities"},
    {"symbol": "SLV", "label": "iShares Silver Trust", "group": "Commodities"},
    {"symbol": "GDX", "label": "Gold Miners", "group": "Commodities"},
    {"symbol": "USO", "label": "United States Oil Fund", "group": "Commodities"},
    {"symbol": "UNG", "label": "United States Natural Gas", "group": "Commodities"},
    {"symbol": "DBA", "label": "Invesco Agriculture", "group": "Commodities"},
    {"symbol": "CPER", "label": "United States Copper Index", "group": "Commodities"},
    {"symbol": "EFA", "label": "MSCI EAFE", "group": "International"},
    {"symbol": "FEZ", "label": "Euro Stoxx 50", "group": "International"},
    {"symbol": "EWJ", "label": "Japan", "group": "International"},
    {"symbol": "FXI", "label": "China Large-Cap", "group": "International"},
    {"symbol": "EEM", "label": "Emerging Markets", "group": "International"},
    {"symbol": "INDA", "label": "India", "group": "International"},
    {"symbol": "SMH", "label": "VanEck Semiconductor", "group": "Thematic"},
    {"symbol": "SOXX", "label": "iShares Semiconductor", "group": "Thematic"},
    {"symbol": "XBI", "label": "SPDR Biotech", "group": "Thematic"},
    {"symbol": "IYR", "label": "US Real Estate", "group": "Thematic"},
    {"symbol": "KRE", "label": "Regional Banks", "group": "Thematic"},
    {"symbol": "XME", "label": "Metals & Mining", "group": "Thematic"},
    {"symbol": "XHB", "label": "Homebuilders", "group": "Thematic"},
    {"symbol": "ITB", "label": "US Home Construction", "group": "Thematic"},
    {"symbol": "ARKK", "label": "ARK Innovation", "group": "Thematic"},
    {"symbol": "BITO", "label": "Bitcoin Strategy", "group": "Digital Assets"},
    {"symbol": "BLOK", "label": "Blockchain ETF", "group": "Digital Assets"},
]

SECTOR_ETF_BENCHMARK = {"symbol": "SPY", "label": "S&P 500"}
